
PYTHON=python3

all: josab01 josab02 josab03 josab04 josab05 josab06 

josab01: 
	$(PYTHON) simo-josab-01-BSBS-1umcylwg-SiO2.py

josab02: 
	$(PYTHON) simo-josab-02-BSBS-450x200nmrectwg-Si.py
	$(PYTHON) simo-josab-02b-BSBS-acbands-450x200nmrectwg-Si.py

josab03: 
	$(PYTHON) simo-josab-03-FSBS-1umcylwg-SiO2.py

josab04: 
	$(PYTHON) simo-josab-04-FSBS-450x200nmrectwg-Si.py

josab05: 
	$(PYTHON) simo-josab-05-IFSBS-1umcylwg-SiO2.py

josab06: 
	$(PYTHON) simo-josab-06-IFSBS-450x200nmrectwg-Si.py
