
PYTHON=python3

all: josab01 josab02 josab03 josab04 josab05 josab06 josab07 

josab01: 
	$(PYTHON) simo-josab-BSBS-1umcylwg-SiO2.py
josab02: 
	$(PYTHON) simo-josab-BSBS-450x200nmrectwg-Si.py
josab03: 
	$(PYTHON) simo-josab-BSBS-acbands-450x200nmrectwg-Si.py
josab04: 
	$(PYTHON) simo-josab-FSBS-1umcylwg-SiO2.py
josab05: 
	$(PYTHON) simo-josab-FSBS-450x200nmrectwg-Si.py
josab06: 
	$(PYTHON) simo-josab-IFSBS-1umcylwg-SiO2.py
josab07: 
	$(PYTHON) simo-josab-IFSBS-450x200nmrectwg-Si.py

