
examples: 
	cd tutorials && make 
	cd lit_examples && make 
	cd josab_tutorial && make 

fastexamples: 
	cd tutorials && make allfast 
	cd lit_examples && make allfast 
	cd josab_tutorial && make allfast

clean:
	make -C tutorials clean
	make -C lit_examples clean
	make -C josab_tutorial clean
